import type { ExamSettings, ExamData, VersionMapping } from '../types';

export function escapeLatex(text: string): string {
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\$/g, '\\$')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/#/g, '\\#')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/_/g, '\\_')
    .replace(/~/g, '\\textasciitilde{}');
}

export function generateLatexDocument(
  settings: ExamSettings,
  masterExam: ExamData,
  versions: ExamData[],
  mappings: VersionMapping[],
  allowTrustedTex = false
): string {
  const processText = allowTrustedTex ? (text: string) => text : escapeLatex;
  
  const coverMetadata = `
% Generated by Exam Generator
% University: ${settings.university}
% Department: ${settings.department}
% Course: ${settings.coursecode}
% Exam: ${settings.examname}
% Date: ${settings.examdate}
% Time: ${settings.timeallowed}
% Paper Size: ${settings.paper_size}
`;

  const masterSection = `
%====================
% MASTER EXAM
%====================
\\section*{${processText(settings.examname)} - Master}
\\textbf{University:} ${processText(settings.university)} \\\\
\\textbf{Department:} ${processText(settings.department)} \\\\
\\textbf{Course:} ${processText(settings.coursecode)} \\\\
\\textbf{Term:} ${processText(settings.term)} \\\\
\\textbf{Date:} ${processText(settings.examdate)} \\\\
\\textbf{Time Allowed:} ${processText(settings.timeallowed)}

\\begin{enumerate}
${masterExam.questions.map((question, index) => `
  \\item ${processText(question.text)}
  \\begin{enumerate}
${question.choices[0].map((choice, choiceIndex) => `    \\item[${String.fromCharCode(65 + choiceIndex)})] ${processText(choice.text)}`).join('\n')}
  \\end{enumerate}
`).join('')}\\end{enumerate}

\\newpage
`;

  const versionSections = versions.map((version, versionIndex) => {
    const versionLabel = version.name.replace('version_', '');
    return `
%====================
% VERSION ${versionLabel}
%====================
\\section*{${processText(settings.examname)} - ${settings.code_name} ${versionLabel}}
\\textbf{University:} ${processText(settings.university)} \\\\
\\textbf{Department:} ${processText(settings.department)} \\\\
\\textbf{Course:} ${processText(settings.coursecode)} \\\\
\\textbf{Term:} ${processText(settings.term)} \\\\
\\textbf{Date:} ${processText(settings.examdate)} \\\\
\\textbf{Time Allowed:} ${processText(settings.timeallowed)} \\\\
\\textbf{${settings.code_name}:} ${versionLabel}

\\begin{enumerate}
${version.questions.map((question, index) => `
  \\item ${processText(question.text)}
  \\begin{enumerate}
${question.choices[0].map((choice, choiceIndex) => `    \\item[${String.fromCharCode(65 + choiceIndex)})] ${processText(choice.text)}`).join('\n')}
  \\end{enumerate}
`).join('')}\\end{enumerate}

\\newpage
`;
  }).join('');

  const mappingTable = `
%====================
% MAPPING TABLE
%====================
\\section*{Answer Key and Mapping}

\\begin{longtable}{|c|c|c|c|c|c|c|}
\\hline
\\textbf{Group} & \\textbf{Master Q} & \\textbf{Version} & \\textbf{Version Q} & \\textbf{Permutation} & \\textbf{Correct} & \\textbf{Points} \\\\
\\hline
\\endhead
${mappings.map(mapping => 
  `${mapping.group} & ${mapping.masterQNo} & ${mapping.version} & ${mapping.versionQNo} & ${mapping.perm} & ${mapping.correct} & ${mapping.points || 1} \\\\`
).join('\n\\hline\n')}
\\hline
\\end{longtable}
`;

  return `\\documentclass[${settings.paper_size.toLowerCase()}paper,11pt]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{geometry}
\\usepackage{enumerate}
\\usepackage{longtable}
\\usepackage{amsmath}
\\usepackage{amsfonts}
\\usepackage{amssymb}

\\geometry{margin=1in}
\\title{${processText(settings.examname)}}
\\author{${processText(settings.department)}}
\\date{${processText(settings.examdate)}}

\\begin{document}

${coverMetadata}

${masterSection}

${versionSections}

${mappingTable}

\\end{document}`;
}

export function generateMappingCSV(mappings: VersionMapping[]): string {
  const headers = ['Group', 'Master Q#', 'Version', 'Version Q#', 'Permutation', 'Correct', 'Points'];
  const rows = mappings.map(m => [
    m.group.toString(),
    m.masterQNo.toString(),
    m.version,
    m.versionQNo.toString(),
    m.perm,
    m.correct,
    (m.points || 1).toString()
  ]);
  
  return [headers, ...rows].map(row => row.join(',')).join('\n');
}